sudo: false

cache:
    directories:
        - $HOME/doxygen

before_script:
    # download doxygen 1.8.12
    - mkdir -p $HOME/doxygen
    - cd $HOME/doxygen
    - ls doxygen* >/dev/null 2>&1 || curl -L ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.12.linux.bin.tar.gz | tar xz

script:
    - set -e
    - cd $TRAVIS_BUILD_DIR
    - python $TRAVIS_BUILD_DIR/.travis.d/definition_check.py
    - bash $TRAVIS_BUILD_DIR/.travis.d/download_sdk.sh
    - export VITASDK=$PWD/vitasdk
    - export PATH=$VITASDK/bin:$PATH
    - cd $VITASDK/arm-vita-eabi/include
    - rm -rf psp2 psp2kern vitasdk vitasdk.h
    - cd $VITASDK/arm-vita-eabi/lib
    - rm -rf *_stub.a
    - cd $TRAVIS_BUILD_DIR
    - cp -r include/* $VITASDK/arm-vita-eabi/include
    - vita-libs-gen db.yml output
    - cd output
    - make
    - cp *_stub.a $VITASDK/arm-vita-eabi/lib
    - cd $TRAVIS_BUILD_DIR
    - git clone https://github.com/vitasdk/samples
    - cd samples
    - for f in */Makefile; do make -C ${f%/*} all; done
before_deploy:
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"

deploy:
    provider: script
    overwrite: true
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.travis.d/deploy_docs.sh
    on:
        tags: false
        branch:
            - master
