language: c
dist: focal
sudo: false

addons:
    apt:
      packages:
        - libclang1-9
        - libclang-cpp9

cache:
    directories:
        - $HOME/downloads

before_script:
    - bash $TRAVIS_BUILD_DIR/.travis.d/download_external_apps.sh

script:
    - set -e
    - cd $TRAVIS_BUILD_DIR
    - bash $TRAVIS_BUILD_DIR/.travis.d/download_sdk.sh
    - export VITASDK=$PWD/vitasdk
    - export PATH=$VITASDK/bin:$PATH
    - export INCLUDE_DIR=$TRAVIS_BUILD_DIR/include
    # Make sure headers are valid
    - find $INCLUDE_DIR -type f -name "*.h" | xargs -I FN -n 1 -P 4 arm-vita-eabi-gcc -I$INCLUDE_DIR -c FN -o /dev/null
    - find $INCLUDE_DIR -type f -name "*.h" | xargs -I FN -n 1 -P 4 arm-vita-eabi-g++ -I$INCLUDE_DIR -c FN -o /dev/null
    - bash $TRAVIS_BUILD_DIR/.travis.d/download_external_libs.sh
    - cd $VITASDK/arm-vita-eabi/include
    - rm -rf psp2 psp2kern vitasdk vitasdk.h
    - cd $VITASDK/arm-vita-eabi/lib
    - rm -rf *_stub.a
    - cd $TRAVIS_BUILD_DIR
    - cp -r include/* $VITASDK/arm-vita-eabi/include
    - USE_LINT=1 python build.py output
    - cd $TRAVIS_BUILD_DIR
    - git clone https://github.com/vitasdk/samples
    - cd samples
    - mkdir build
    - cd build
    - cmake ..
    - make

before_deploy:
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"

deploy:
    provider: script
    overwrite: true
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.travis.d/deploy_docs.sh
    on:
        tags: false
        branch:
            - master
